[project]
name = "device-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David", email = "davidfranco291@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic[email]>=2.13.4",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
device-systems = "device_systems:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
